package io.vdubovsky.statemachineexample.statemachine.configuration.pingpong;

public enum Event {
    PING_PONG_TO_SET_ACTION_PING_EVENT,
    PING_PONG_TO_SET_ACTION_PONG_EVENT,
    PING_PONG_TO_SET_EXTERNAL_REQUEST_EVENT,
    PING_PONG_TO_PLAY_EVENT,
    PING_PONG_TO_SET_RESPONSE_EVENT,
    PING_PONG_TO_SET_COUNTER_EVENT,
    PING_PONG_TO_OUT_EVENT
}
